name: Deploy Angular App to Firebase

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ensure this matches your Angular project's Node version

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Angular app
    - name: Build Angular App
      run: npm run build -- --prod

    # Step 5: Deploy to Firebase Hosting
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2.2.2
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
